#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(remarvin)
pkgdesc="Multi-account and device encryption manager"
url="https://github.com/plan5/remarvin"
pkgver=0.1.1-1
timestamp=2022-07-18T22:00Z
section=rmall
maintainer="plan5 <plan5 30434574+plan5@users.noreply.github.com>"
license=GPLv3
_srcver="v${pkgver%-*}"
source=(
    https://github.com/plan5/remarvin/archive/refs/tags/$_srcver.zip
)
sha256sums=(
    9c19de9ae59d7d0d1ddcfcdf3af15e6fb3dfaf2d2039d20c27dbcc01b17bc088
)
installdepends=(gocryptfs simple)

package() {
    install -D -m 755 "$srcdir"/remarvin.sh "$pkgdir"/opt/bin/remarvin.sh
    install -D -m 644 "$srcdir"/icon256.png -t "$pkgdir"/opt/etc/draft/icons/remarvin.png
    install -D -m 644 "$srcdir"/remarvin.draft "$pkgdir"/opt/etc/draft/ 
}
